useDotenv: true
service: serverless-bolt-js
frameworkVersion: "3"
provider:
  name: aws
  runtime: nodejs16.x
  memorySize: 1024
  timeout: 10
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    OPENAI_SECRET_KEY: ${env:OPENAI_SECRET_KEY}
    EXTERNAL_SERVER_PORT: ${env:EXTERNAL_SERVER_PORT}
    EXTERNAL_SERVER_HOST: ${env:EXTERNAL_SERVER_HOST}
functions:
  slack:
    handler: src/main.handler
    events:
      - http:
          path: slack/events
          method: post
      - sqs: ${env:MESSAGE_QUEUE_ARN}
plugins:
  - serverless-offline
